user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

device:
    resource: "@DeviceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
